version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-local
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./js:/usr/share/nginx/html/developwl/js/
    ports:
      - 3050:3050
      #- 443:443